### PR TITLE
Migrates to rlesouef/alpine, removes nargs from cmd param, adds ssh a…

### PR DESCRIPTION
**Pull request by DanielButAtWork**
…nd git to the image

### CODE REVIEW

**Comment by DanielButAtWork** [comment]
Our company (WikiTeq) is going through our forks and seeing if any of our changes are useful to the upstreams - @nilbus what are your thoughts? I see that you haven't touched this repo in a while, but hopefully you are still around?

**Comment by nilbus** [comment]
Thanks for the contribution! I'm sure that if this has been useful to you, then it's a change worth keeping.

I do not use this repo any more and won't be testing it. 

I'm glad this has been helpful for you!

**Comment by nilbus** [comment]
If you ever have a need to make further changes to this repo and would benefit from being a direct contributor, I'll be happy to add you as a maintainer.

**Comment by DanielButAtWork** [comment]
> If you ever have a need to make further changes to this repo and would benefit from being a direct contributor, I'll be happy to add you as a maintainer.

Thank you, but at the moment I don't think we will be making any more changes, but if we do I'll let you know

**Comment by DanielButAtWork** [comment]
Would you mind tagging a new version at https://hub.docker.com/r/nilbus/docker-hook/tags though, so that we can use it directly?

**Comment by nilbus** [comment]
Goody idea! I’ll do that soon and post back here.

**Comment by nilbus** [comment]
Done!
https://hub.docker.com/r/nilbus/docker-hook/tags
nilbus/docker-hook:latest

**Comment by DanielButAtWork** [comment]
I see there is a `latest` - would it be possible to add a tag specific to this version, so that we don't have unexpected updates if a new version is published? E.g. `:2024-12` for December 2024?

**Comment by nilbus** [comment]
Good idea. Done! docker-hook:2024-12 and docker-hook-2017-02 (previous
:latest).

**Comment by DanielButAtWork** [comment]
Thanks so much - that should be everything we need to stop using our fork

**Pull request merged**
